---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Print message
      debug:
        msg: Hello Ansible World
    
    - community.general.homebrew:
        name: asciidoctor
        state: present
