---
- hosts: localhost
  connection: local

  tasks:
    - name: Print message
      debug:
        msg: Hello Ansible World
    
    - community.general.homebrew:
        become: true
        become_user: robertcotter
        name: asciidoctor
        state: present
