---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Print message
      debug:
        msg: Hello Ansible World

    - name: get the username running the deploy
      become: false
      local_action: command whoami
    
    - community.general.homebrew:
        name: asciidoctor
        state: present
      become: true
      become_user: robertcotter