---
- hosts: localhost
  connection: local
  become: true

  # vars:
  #   remote_user: robertcotter

  tasks:
    - include_vars: vars.yaml

    - name: Print message
      debug:
        msg: Hello Ansible World

    - name: Get the username running the deploy
      become: false
      debug: msg="{{ lookup('env','USER') }}"
    
    # - name: Download Packages
    #   become: true
    #   become_user: robertcotter
    #   community.general.homebrew:
    #     name: asciidoctor
    #     state: present

    - name: Download Packages
      become: true
      become_user: robertcotter
      package:
        name: "{{ brew_items }}"
        state: present
    
    - name: Copy file
      remote_user: "{{ remote_user }}"
      copy:
        src: files/foo.txt
        dest: /Users/{{ remote_user }}/Desktop