---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Print message
      debug:
        msg: Hello Ansible World
    
    - block: 
      become: true
      become_user: robertcotter
        - community.general.homebrew:
            name: asciidoctor
            state: present
