---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Print message
      debug:
        msg: Hello Ansible World

    - name: get the username running the deploy
      become: false
      debug: msg="{{ lookup('env','USER') }}"
    
    - name: download asciidoctor
      become: true
      become_user: robertcotter
      debug: msg="{{ lookup('env','USER') }}"
      community.general.homebrew:
        name: asciidoctor
        state: present
      