---
- hosts: localhost
  connection: local
  become: true
  become_user: robertcotter

  tasks:
    - name: Print message
      debug:
        msg: Hello Ansible World
    
    - community.general.homebrew:
        name: asciidoctor
        state: present
